version: '3.7'
services:
  app:
    image: sammiio/gifserver
    build: .
    environment:
      # place your API key in .env
      GIPHY_API_KEY: ${GIPHY_API_KEY}
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
